name: Security & Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: |
          echo "Running security audit..."
          pnpm audit --audit-level moderate || {
            echo "Security audit found issues. Checking severity..."
            if pnpm audit --audit-level high; then
              echo "No high/critical vulnerabilities found. Proceeding..."
              exit 0
            else
              echo "High or critical vulnerabilities found!"
              exit 1
            fi
          }

      - name: Check for outdated dependencies
        run: pnpm outdated || true
